<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grim Hollow — модерация</title>
<style>body{max-width:1000px;margin:40px auto;background:#202528;color:#e1c790;font:16px Tahoma;padding:20px}h1{font-family:Georgia}input,button,textarea{font:inherit;padding:10px;margin:4px;background:#3b4142;color:#fff;border:1px solid #8b7954}article{border:1px solid #78664c;padding:20px;margin:16px 0}small{color:#aeb6b4}#status{min-height:30px}textarea{width:85%}</style>
<h1>GRIM HOLLOW · Жалобы</h1><p>Вход для аккаунта с правами модератора. Решения записываются в журнал.</p>
<form id="login"><input id="email" type="email" placeholder="Email" required autocomplete="username"><input id="password" type="password" placeholder="Пароль" required autocomplete="current-password"><button>Войти</button></form>
<button id="refresh">Обновить</button><button id="logout">Выйти</button><p id="status" role="status"></p><main id="reports"></main>
<script>
(()=>{let token='';const el=id=>document.getElementById(id);async function api(path,body){const r=await fetch('/api/v1/'+path,{method:body?'POST':'GET',headers:{'Accept':'application/json','Content-Type':'application/json',Authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined});if(r.status===204)return {};const d=await r.json();if(!r.ok)throw Error(d.message||r.status);return d;}
async function refresh(){try{const d=await api('admin/reports');el('reports').replaceChildren();for(const report of d.items){const a=document.createElement('article'),title=document.createElement('strong'),body=document.createElement('p'),why=document.createElement('p'),reason=document.createElement('textarea');title.textContent='#'+report.id+' · '+report.name;body.textContent=report.body;why.textContent='Жалоба: '+report.reason;reason.placeholder='Основание решения (обязательно)';a.append(title,body,why,reason);for(const [caption,action] of [['Отклонить','dismiss'],['Ограничить чат на 60 минут','mute']]){const b=document.createElement('button');b.textContent=caption;b.onclick=async()=>{try{await api('admin/reports',{report_id:report.id,action,minutes:60,reason:reason.value});await refresh();}catch(e){el('status').textContent=e.message;}};a.append(b);}el('reports').append(a);}el('status').textContent='Открытых жалоб: '+d.items.length;}catch(e){el('status').textContent=e.message;}}
el('login').onsubmit=async e=>{e.preventDefault();try{token=(await api('auth/login',{email:el('email').value,password:el('password').value})).access_token;el('password').value='';await refresh();}catch(e){el('status').textContent=e.message;}};
el('refresh').onclick=refresh;el('logout').onclick=async()=>{try{if(token)await api('auth/logout',{});}finally{token='';el('reports').replaceChildren();el('status').textContent='Вы вышли.';}};
})();</script></html>
